### ISSUE TITLE
Cannot find "all-disambiguation-titles" file

### ISSUE THREAD

**Issue by kukkipareek** [1ngrid/Master-Thesis-2015#2]
when running through the file Split_categorylinks.py was not able to understand where to extract the all-disambiguation-titles file from.

**Comment by moe18** [comment]
> when running through the file Split_categorylinks.py was not able to understand where to extract the all-disambiguation-titles file from.

same here

**Comment by ingridguren** [comment]
Thanks for reaching out. This project is connected to my master thesis, finished three years ago, and is therefore not updated anymore. To answer your question: The all-disambiguation-titles.txt.gz is from Wikipedia's own list of disambiguous pages/articles (https://en.wikipedia.org/wiki/Category:All_disambiguation_pages) and was downloaded directly from Wikipedia dump's database.

**Comment by ingridguren** [comment]
I will close the issue since this project is not maintained.

**Comment by srinandsk** [comment]
Appreciate if you could you please send the link to the file all-disambiguation-titles.txt.gz or upload the file itself on to github. I am not able to find this anywhere.
Thanks
